# Generated by Django 5.0.6 on 2024-07-28 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourrierDepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortie', models.DateTimeField(blank=True, null=True)),
                ('destinerA', models.CharField(max_length=100)),
                ('objet', models.TextField()),
                ('fichier', models.FileField(upload_to='courriers/')),
                ('nombrePiecesJointes', models.IntegerField(default=1)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('incremented_number', models.IntegerField(default=0, editable=False)),
                ('numero', models.CharField(editable=False, max_length=50, null=True)),
                ('support', models.CharField(max_length=255, null=True)),
                ('etablissment', models.CharField(max_length=255, null=True)),
                ('entrer', models.DateTimeField(null=True)),
                ('Nbentrer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('etablissement_type', models.CharField(choices=[('Ecole', 'Ecole'), ('Faculte', 'Faculte'), ('Ministre', 'Ministre'), ('Prefecture', 'Prefecture')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('pole_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suport',
            fields=[
                ('suport_id', models.AutoField(primary_key=True, serialize=False)),
                ('suport', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TransferReason',
            fields=[
                ('transfer_reason_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('SupAdmin', 'SupAdmin'), ('Utilisateur', 'Utilisateur'), ('chef', 'chef'), ('chefservice', 'chefService'), ('responsableservice', 'responsableService'), ('vicepresident', 'vicePresident'), ('responsablePôle', 'responsablePôle'), ('chefdivision', 'chefDivision'), ('secretairegeneral', 'secretaireGeneral'), ('chefcentre', 'chefCentre')], max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('pole', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pole', to='GestionCourriers.pole')),
                ('service', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='GestionCourriers.service')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incremented_number', models.IntegerField(default=0, editable=False)),
                ('commentaire', models.TextField()),
                ('raison', models.CharField(max_length=255)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('support', models.CharField(max_length=255, null=True)),
                ('etablissment', models.CharField(max_length=255, null=True)),
                ('entrer', models.DateTimeField(null=True)),
                ('Nbentrer', models.IntegerField(null=True)),
                ('objet', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('fichier', models.FileField(upload_to='courriers/')),
                ('nombre_pieces_jointes', models.IntegerField(blank=True, null=True)),
                ('numero', models.CharField(editable=False, max_length=50, null=True)),
                ('courrier_depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='GestionCourriers.courrierdepart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_user', to='GestionCourriers.user')),
                ('user_service', models.ManyToManyField(related_name='courriers_transferer', to='GestionCourriers.user')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='chief',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chief_of_service', to='GestionCourriers.user'),
        ),
        migrations.AddField(
            model_name='courrierdepart',
            name='destinerAId',
            field=models.ManyToManyField(related_name='courriers_recus', to='GestionCourriers.user'),
        ),
        migrations.AddField(
            model_name='courrierdepart',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCourriers.user'),
        ),
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortie', models.DateTimeField(blank=True, null=True)),
                ('objet', models.TextField()),
                ('fichier', models.FileField(upload_to='courriers/')),
                ('nombrePiecesJointes', models.IntegerField(default=1)),
                ('incremented_number', models.IntegerField(default=0, editable=False)),
                ('numero', models.CharField(editable=False, max_length=50, null=True)),
                ('support', models.CharField(max_length=255, null=True)),
                ('etablissment', models.CharField(max_length=255, null=True)),
                ('traitePar', models.CharField(max_length=100)),
                ('signePar', models.CharField(max_length=100)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCourriers.user')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedCourrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incremented_number', models.IntegerField(default=0, editable=False)),
                ('numero', models.CharField(editable=False, max_length=50, null=True)),
                ('sortie', models.DateTimeField(blank=True, null=True)),
                ('destinerA', models.CharField(max_length=100)),
                ('objet', models.TextField()),
                ('fichier', models.FileField(upload_to='courriers/')),
                ('nombrePiecesJointes', models.IntegerField(default=1)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('numeroOrdre', models.CharField(max_length=100)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('support', models.CharField(max_length=255, null=True)),
                ('etablissment', models.CharField(max_length=255, null=True)),
                ('entrer', models.DateTimeField(null=True)),
                ('Nbentrer', models.IntegerField(null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_courriers', to='GestionCourriers.user')),
                ('destinerAId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courrier_Archiver', to='GestionCourriers.user')),
            ],
        ),
    ]
