# Generated by Django 5.0.6 on 2024-07-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCourriers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='departement',
            name='telephone_fixe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departement',
            name='ville',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='departement',
            name='etablissement_type',
            field=models.CharField(choices=[('École', 'École'), ('Faculté', 'Faculté'), ('Ministère', 'Ministère'), ('Prefecture', 'Prefecture'), ('Université', 'Université'), ('Province', 'Province'), ('Commune', 'Commune'), ('Institut', 'Institut')], max_length=50),
        ),
    ]
