# Generated by Django 5.0.6 on 2024-07-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCourriers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrierdepart',
            name='numero',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
