# Generated by Django 5.0.6 on 2024-07-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCourriers', '0002_courrierdepart_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Utilisateur', 'Utilisateur'), ('chef', 'chef'), ('chefservice', 'chefservice')], max_length=50),
        ),
    ]
