# Generated by Django 5.0.6 on 2024-07-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCourriers', '0002_departement_email_departement_telephone_fixe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='telephone_fixe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
