# Generated by Django 5.0.6 on 2024-07-12 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCourriers', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='numero_bureau_ordre',
        ),
    ]
