# Generated by Django 5.0.6 on 2024-08-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCourriers', '0003_alter_departement_telephone_fixe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='etablissement_type',
            field=models.CharField(max_length=255),
        ),
    ]
