# Generated by Django 5.0.6 on 2024-07-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCourriers', '0004_remove_transfer_numero_bureau_ordre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='service',
        ),
    ]
