# Generated by Django 5.0.6 on 2024-07-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCourriers', '0005_remove_transfer_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courrierdepart',
            name='destinerAId',
        ),
        migrations.AddField(
            model_name='courrierdepart',
            name='destinerAId',
            field=models.ManyToManyField(related_name='courriers_recus', to='GestionCourriers.user'),
        ),
    ]
