# Generated by Django 5.0.6 on 2024-07-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCourriers', '0006_remove_courrierdepart_destineraid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='user_service',
        ),
        migrations.AddField(
            model_name='transfer',
            name='user_service',
            field=models.ManyToManyField(related_name='courriers_transferer', to='GestionCourriers.user'),
        ),
    ]
