# Generated by Django 5.0.6 on 2024-07-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCourriers', '0007_remove_transfer_user_service_transfer_user_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedcourrier',
            name='destinerAId',
        ),
        migrations.AddField(
            model_name='archivedcourrier',
            name='destinerAId',
            field=models.ManyToManyField(related_name='courriers_archiver', to='GestionCourriers.user'),
        ),
    ]
