# Generated by Django 5.0.6 on 2024-07-12 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCourriers', '0008_remove_archivedcourrier_destineraid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedcourrier',
            name='destinerAId',
        ),
        migrations.AddField(
            model_name='archivedcourrier',
            name='destinerAId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courrier_Archiver', to='GestionCourriers.user'),
        ),
    ]
